dependencies {
    implementation libs.bundles.anvillib
    interfaceInjectionData libs.anvillib.font
    jarJar libs.bundles.anvillib
    implementation(libs.jhighlight) { transitive = false }
    jarJar libs.jhighlight
    implementation(libs.jsoup) { transitive = false }
    jarJar(libs.jsoup)
}
