[versions]
minecraft = "1.21.1"
neoForge = "21.1.220"
modDevGradle = "2.0.78"
lombok = "8.7.1"
anvillib = "2.0.0+snapshot.222"

[libraries]
anvillib-config = { group = "dev.anvilcraft.lib", name = "anvillib-config-neoforge-1.21.1", version.ref = "anvillib" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
